#!/usr/bin/env bash

readonly es_uri="${ELASTICSEARCH_URI:-localhost:9200}"

list() {
  curl "$es_uri/_cat/indices?v"
}

get() {
  curl "$es_uri/$1" | jq .
}

init() {
  declare index="$1"

  curl -s localhost:9200/${index} -XPUT -d '
  {
    "mappings": {
      "alert": {
        "properties": {
          "metadata": {
            "properties": {
              "location": {"type": "geo_point"}
            }
          }
        }
      }
    }
  }'
}

"$@"
