#!/bin/bash

readonly sink_uri="${SINK_URI:-localhost:9000}"

readonly app_id="ce26f701-64f8-4804-be09-02b5b2ac7acb"


# ExternalEvent(title: String, url: String, text: String, metadata: AlertMeta)

echo curl "$sink_uri/api/alert/$app_id" -H 'content-type: application/json' \
-d '{"title":"Rio de Janeiro Labor Union Unrest", "url":"http://www.google.com", "text":"Labor union protest sparks civil unrest in Rio de Janeiro, reports of property damage and confrontations with police.", "metadata":{"keywords":["labor unions", "unrest", "Rio de Janeiro"],"coordinates":{"x":"-43.243732","y":"-22.813925"}}}'

curl "$sink_uri/api/alert/$app_id" -H 'content-type: application/json' \
-d '{"title":"Rio de Janeiro Credit Union Unrest", "url":"http://www.google.com", "text":"CREDIT union protest sparks civil unrest in Rio de Janeiro, reports of property damage and confrontations with police.", "classification": "unclassified", "metadata":{"keywords":["coffee", "credit unions", "unrest", "Rio de Janeiro"],"coordinates":{"x":"-43.243732","y":"-22.813925"}}}'
