#!/bin/bash

readonly sink_uri="${SINK_URI:-localhost:9000}"
readonly app_name="${1:-default}"
readonly classification="${APP_CLASSIFICATION:-unclassified}"

# Application(name: String)
app=$(curl -s "$sink_uri/api/app" -H 'content-type: application/json' -d "{\"name\":\"$1\", \"classification\":\"$classification\"}")
./es-index init "alert-$app_name"

echo "$app"
