addSbtPlugin("com.lightbend.lagom" % "lagom-sbt-plugin" % "1.3.4")

addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.2.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.0")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC1")
addSbtPlugin("com.typesafe.sbt" %% "sbt-native-packager" % "1.2.0")
addSbtPlugin("com.github.jw3" % "sbt-openshift" % "0.1")
addSbtPlugin("com.github.jw3" % "sbt-artifactory" % "0.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "3.0.2")
